<?php

namespace backend\modules\extractor\controllers;

use Yii;
use yii\web\Controller;

//exported MODELS
use app\models\LoginForm;
use app\models\Center;
use yii\helpers\Url;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use app\models\UserAccess;
use yii\base\ErrorException;

//for testing
use app\models\Common;
use app\models\Lahead;
use app\models\Lastock;

class DefaultController extends Controller{
    
    public $access = array(
        'view' => 152 ,'edit' => 153,'new' => 154,
        'save' => 155,'change' => 156,'delete' => 157,
        'print' => 158,'lock' => 159,'unlock' => 160,
        'changeamount' => 161,'crlimit'=>162,'post' => 163,'unpost' => 164,
        'clickadditem'=>805,'clickedititem'=>806,'clickdeleteitem'=>807);

    public function actionIndex(){
       $this->layout = "@app/views/layouts/backend/main";
       $moduleid = $this->module->id;
       Yii::$app->view->params['moduleid'] = $moduleid;
       return $this->render('index',array('moduleid'=>$moduleid));
    }//emd action index

    public function actionLoadextractiondata(){
      Yii::$app->backend->AjaxVerification($this); 
    	$filter = Yii::$app->backend->sanitize($_GET['exfilter'],'DEFAULT');
    	$forextracting = Yii::$app->extractify->retrieveDatatoExtract($filter);
    	echo json_encode(array('extractiondata'=>$forextracting));
    }//end function extractiondata

    public function actionLoadextractionfilters(){
      Yii::$app->backend->AjaxVerification($this); 
    	$filters = Yii::$app->extractify->retrieveFilters();
    	echo json_encode(array('exfilters'=>$filters));
    }//end function loadExtractionFilters


    //USED BY SEARCHING OF WAREHOUSE ON MODAL GENERATED BY LOOKUP BUTTON
    public function actionWarehouselookupsearch(){
        Yii::$app->backend->AjaxVerification($this);
        $params = $_GET;
        $return=Yii::$app->sbccontroller->sbcWarehouselookupsearch($this,$params);  
        if($return['verifyuser']==1){
           return $this->redirect(Url::to(['/admin/default/login']));
        }elseif($return['verifyaccess']==1){
           return $this->redirect(Url::to(['/admin/default/401']));
        }else{
           echo json_encode(array('searchitems' => $return['data']));
        }                                       
    }//END FUNCTION

    public function actionExtractdata(){
      Yii::$app->backend->AjaxVerification($this); 
      $filter = Yii::$app->backend->sanitize($_GET['exfilter'],'DEFAULT');
      $result = Yii::$app->extractify->createExtractionDocument($filter);
      
      echo json_encode(array('status'=>$result));
    }//end function extract data


    public function actionClearoutwh(){
      try {
      $head = new Lahead;
      $stock = new Lastock;

      Yii::$app->backend->AjaxVerification($this); 
      $whid = Yii::$app->backend->sanitize($_GET['wh'],'DEFAULT');

      $qryheadloop = "select wh.clientid as destinationwhid,wh.clientname as destinationwhname,item.defaultwh as destinationwh,
                      rrstatus.whid as sourcewhid,wh2.clientname as sourcewhname,wh2.client as sourcewh from rrstatus
                      left join item on item.itemid = rrstatus.itemid
                      left join client as wh on wh.client = item.defaultwh
                      left join client as wh2 on wh2.clientid = rrstatus.whid
                      where rrstatus.whid = ".$whid." and rrstatus.bal <> 0
                      group by item.defaultwh,rrstatus.whid";

      $headloopwh = Yii::$app->sbccommon->opentable($qryheadloop);

      if(!empty($headloopwh)){
          foreach ($headloopwh as $key => $value) {
              $params = ['destinationwhid'=>$value['destinationwhid'],'destinationwhname'=>$value['destinationwhname'],'destinationwh'=>$value['destinationwh'],
                        'sourcewhid'=>$value['sourcewhid'],'sourcewhname'=>$value['sourcewhname'],'sourcewh'=>$value['sourcewh']];
              $headreturn = Yii::$app->extractify->createTransactionHead($head,'','TS','TB',$params);
              
              if($headreturn['status']){
                  $stock->trno = $headreturn['trno'];
                  Yii::$app->extractify->createTransactionStock($stock,'','TS',$params);
              }else{
                $status = false;
                $msg = "Error Occured white generating CLEAR OUT Transactions for '".$params['destinationwhname']."'. Please Try Again.";
              }//end if
          }//end for each
          $status = true;
          $msg = "Successfull Extracted Return TS for Clearing Out. Thanks!";
      }else{
        $status = false;
        $msg = "There is no more available stock to clear out on that Van. Please try again.";
      }//end if
      } catch (ErrorException $e) {
        echo $e;
      }

      echo json_encode(['status'=>$status,'msg'=>$msg]);
    }//end action clearout wh
}//end action
