<?php

namespace backend\modules\KL\controllers;

use Yii;
use yii\web\Controller;

use yii\helpers\Url;
use app\models\Webproc;
use app\models\Client;
use yii\base\ErrorException;

class DefaultController extends Controller
{
//TODO: MAKE THIS CONTROLLER ACCESS AVAIALABLE ON JAVASCRIPT TO BE USED ON EVENTS
//THESE ACCESS ARRAY IS USED TO DETERMINE ACCESS INDEX ON ATTRIBUTES
	public $access = array('view' => 3125,'print'=>3125);
    
    //TO TURN OFF CSRFVALIDATION [SO WE CAN USE AJAX]
    public function beforeAction($action){
        Yii::$app->request->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    public function actionVerifyaccess($accesstype,$trno){      
        Yii::$app->backend->AjaxVerification($this); 
        $return = Yii::$app->sbccontroller->jverifyaccess($this,$this->access[$accesstype],$accesstype,$trno);
        echo json_encode(array('verified'=>$return)); 
    }


    public function actionIndex(){
      $return=Yii::$app->sbccontroller->sbcindex($this);        
        if($return['verifyuser']==1){
           return $this->redirect(Url::to(['/admin/default/login']));
        }elseif($return['verifyaccess']==1){
           return $this->redirect(Url::to(['/admin/default/401']));
        }else{
          return $this->render('index',array('moduledata' => $return['moduledata'],'moduleid'=>$return['moduleid']));
        }
    }//END ACTION INDEX


    public function actionAgentlookupsearch(){
        Yii::$app->backend->AjaxVerification($this); 
        $searchstring = $_GET['searchstring'];
        $searchagent = Yii::$app->backend->searchagents($this,$this->access['view'],$searchstring);
        echo json_encode(array('searchagent' => $searchagent));
    } //END ACTION CUSTOMER LOOKUP SEARCH

    public function actionCreatecollectionlist(){
        $msg = '';
        Yii::$app->sbccommon->execqry('truncate kldetail');
        Yii::$app->sbccommon->execqry('truncate klhead');

        Yii::$app->backend->AjaxVerification($this); 
        $params = Yii::$app->backend->sanitize($_GET,'ARRAY');
        $agentdetails = explode("~", $params['agent']);
        $qry = "insert into klhead (agentcode,notes) values('".$agentdetails[0]."','".$params['notes']."')";
        $status = Yii::$app->sbccommon->execqry($qry);
        
        if($status){
            $retrieveqry = "insert into kldetail (trno,clientid,docno,docdate,docduedate,db,cr,amt,doc,client,clientname)
            select ledger.trno,client.clientid,ledger.docno,left(ledger.dateid,10) as dateid,glhead.due,ledger.db,
            case when cntnum.doc = 'CM' then ledger.cr else (ledger.db - ledger.bal) end as cr,
            case when cntnum.doc = 'CM' then abs(ledger.db-ledger.cr) else (ledger.db) - (ledger.db - ledger.bal) end as amt,
            cntnum.doc,client.client,client.clientname from arledger as ledger
            left join glhead on glhead.trno = ledger.trno
            left join cntnum on cntnum.trno = ledger.trno
            left join client on client.clientid = ledger.clientid and  client.iscustomer = 1
            where ledger.bal <> 0 and client.agent = '".$agentdetails[0]."'
            ";
            
            $status = Yii::$app->sbccommon->execqry($retrieveqry);
            
            if(!$status){
                $msg = "An error occured while creating new collection list. Please try again/";
                Yii::$app->sbccommon->execqry('truncate kldetail');
                Yii::$app->sbccommon->execqry('truncate klhead');
            }//end if
        }else{
            $msg = 'Failed to create new Collection list. Please try again.';
        }//end if

        echo json_encode(['status'=>$status,'msg'=>$msg]);
    }//ned function create collection list

    public function actionRetrievecollectionlist(){
        Yii::$app->backend->AjaxVerification($this); 
        $qryhead = "select agentcode,agent.clientname as agentname,notes from klhead
                    left join client as agent on agent.client = klhead.agentcode";
        $head = Yii::$app->sbccommon->openTable($qryhead);

        $qrydetail = "select line,trno,clientid,docno,docdate,docduedate,
        round(db,".Yii::$app->systemsettings->setDecimaldisplay('currency').") as db,
        round(cr,".Yii::$app->systemsettings->setDecimaldisplay('currency').") as cr,
        round(amt,".Yii::$app->systemsettings->setDecimaldisplay('currency').") as amt,
        doc,client,clientname from kldetail";

        $detail = Yii::$app->sbccommon->openTable($qrydetail);

        echo json_encode(['head'=>$head,'detail'=>$detail]);
    }//end function retrieve collection list

    //USED BY SEARCHING OF CUSTOMER ON MODAL GENERATED BY LOOKUP BUTTON
    public function actionCustomerlookupsearch(){
        Yii::$app->backend->AjaxVerification($this);
        $params = $_GET;        
        $return=Yii::$app->sbccontroller->sbcSupplierlookupsearch($this,$params);  
        if($return['verifyuser']==1){
           return $this->redirect(Url::to(['/admin/default/login']));
        }elseif($return['verifyaccess']==1){
           return $this->redirect(Url::to(['/admin/default/401']));
        }else{
           echo json_encode(array('searchclient' => $return['data']));
        }                                       
    }

    public function actionGetklunpaid(){
    try {
        Yii::$app->backend->AjaxVerification($this);
        $clientid = Yii::$app->backend->sanitize($_GET['q'],'DEFAULT');
        $ccode = Client::getclient($clientid);
        $unpaid = Yii::$app->backend->requestUnpaidAccounts($this->module->id,$ccode,'');
        echo json_encode(['unpaidacc'=>$unpaid]);
    } catch (ErrorException $e) {
        echo $e;
    }
    }//end function get kl unpaid

    public function actionInsertsinglekl(){
        Yii::$app->backend->AjaxVerification($this);
        $params = Yii::$app->backend->sanitize($_GET,'ARRAY');
        $insertqry = "insert into kldetail (trno,clientid,docno,docdate,docduedate,db,cr,amt,doc,client,clientname)
        select ledger.trno,client.clientid,ledger.docno,left(ledger.dateid,10) as dateid,glhead.due,ledger.db,
        case when cntnum.doc = 'CM' then ledger.cr else (ledger.db - ledger.bal) end as cr,
        case when cntnum.doc = 'CM' then abs(ledger.db-ledger.cr) else (ledger.db) - (ledger.db - ledger.bal) end as amt,
        cntnum.doc,client.client,client.clientname from arledger as ledger
        left join glhead on glhead.trno = ledger.trno
        left join cntnum on cntnum.trno = ledger.trno
        left join client on client.clientid = ledger.clientid and  client.iscustomer = 1
        where ledger.bal <> 0 and ledger.trno = ".$params['q']." and ledger.line = ".$params['line']."";
        $status = Yii::$app->sbccommon->execqry($insertqry);

        if($status){
            $msg = '';
        }else{
            $msg = "Error inserting UNPAID AR, Please try again.";
        }//end if

        echo json_encode(['status'=>$status,'msg'=>$msg]);
    }//end function

    public function actionRemoveklentry(){
        Yii::$app->backend->AjaxVerification($this);
        $params = Yii::$app->backend->sanitize($_GET,'ARRAY');
        $deleteqry = "delete from kldetail where trno = ".$params['q']." and line=".$params['line']."";
        $status = Yii::$app->sbccommon->execqry($deleteqry);
        
        if($status){
            $msg = 'Successfully removed the Unpaid Entry!';
        }else{
            $msg = "Error removing the Unpaid Entry. Please try again later.";
        }//end if

        echo json_encode(['status'=>$status,'msg'=>$msg]);
    }//end function

}//END CONTROLLER



