<?php

namespace backend\modules\branchmasterfile\controllers;

use Yii;
use yii\web\Controller;
use yii\helpers\Url;

use app\models\Center;

class DefaultController extends Controller{

     public $access = array(
        'view' => 651);

    //TO TURN OFF CSRFVALIDATION [SO WE CAN USE AJAX]
    public function beforeAction($action){
        Yii::$app->request->enableCsrfValidation = false;
        return parent::beforeAction($action);
    }

    //FOR INDEX LOADING OF DATA

     public function actionIndex(){   
        if(Yii::$app->systemsettings->setBranchAccess()){
            if(isset(Yii::$app->session['loggeduser'])){
                $this->layout = "@app/views/layouts/backend/main";
                $center = new Center();
                $data = $center->getbranches_($this,$this->access['view']);  
                $moduleid = $this->module->id;
                Yii::$app->view->params['moduleid'] = $moduleid;
                return $this->render('index',array('centerdata'=>$data,'moduleid'=>$moduleid));
            }else{
                return $this->redirect(Url::to(['/admin/default/login']));
            }//END IF
        }else{
            return $this->redirect(Url::to(['/admin/default/401']));
        }//end if
    }//END ACTION INDEX


    public function actionEditmasterfile(){   
        $line = $_GET['line'];
        $moduleid = $this->module->id;
        $center = new Center();
        $data = $center->getbranches_line($line);
        echo json_encode(array('centerdata' => $data));
        //var_dump($data);
    }//END ACTION EDITMASTERFILE

    public function actionInsertmasterfile(){
        $center = new Center();
        $code = $_GET['code'];
        $name = $_GET['name'];
        $addr = $_GET['addr'];
        $tel = $_GET['tel'];
        $station = $_GET['station'];
        $wh = $_GET['wh'];
        $moduleid = $this->module->id;
        $status = Yii::$app->sbccommon->execqry("insert into center (code, name, address, tel,station, warehouse,editby) values ('$code','$name','$addr','$tel','$station','$wh','".Yii::$app->session['loggeduser']['username']."')");
        $data = $center->getbranches_();
        echo json_encode(array('centerdata' => $data,'status'=>$status));
    }//END ACTION EDIT

    public function actionUpdatemasterfile(){  
        $center = new Center();
        $line = $_GET['line'];
        $code = $_GET['code'];
        $name = $_GET['name'];
        $addr = $_GET['addr'];
        $tel = $_GET['tel'];
        $station = $_GET['station'];
        $wh = $_GET['wh'];
        $moduleid = $this->module->id;
        Yii::$app->sbccommon->execqry("update center set code='$code', name='$name', address='$addr', tel='$tel',station='$station', warehouse='$wh' where line='$line' and code='$code'");
        $data = $center->getbranches_();
        echo json_encode(array('centerdata' => $data));
         //var_dump($aa);
    }//END ACTION EDIT   

    public function actionDeletecenter(){
        $center = new Center();
        $line = $_GET['line'];
        $moduleid = $this->module->id;
        Yii::$app->sbccommon->execqry("delete from center where line='$line'");
        $data = $center->getbranches_();
        echo json_encode(array('centerdata' => $data));
        //var_dump($aa);
    }//END ACTION EDIT

    //USED BY SEARCHING OF WAREHOUSE ON MODAL GENERATED BY LOOKUP BUTTON
    public function actionWarehouselookupsearch(){
        Yii::$app->backend->AjaxVerification($this);
        $params = $_GET;
        $return=Yii::$app->backend->searchBranchWarehouse($params['searchstring']);  
        echo json_encode(array('searchitems' => $return));
    }//end action

}
